

services:
  backend:
    image: golang:1.23rc1-bullseye
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./go:/app
    stdin_open: true
    tty: true
    networks:
      - external

  frontend:
    image: node:22.3.0
    ports:
      - 3000:3000
    volumes:
      - ./js:/app
    stdin_open: true
    tty: true
    networks:
      - external

  mysql:
    container_name: sqldevelop
    image: mysql:oracle
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: chat_develop
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: chatpass001
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
    stdin_open: true
    tty: true
    networks:
      - internal

networks:
  internal:
    internal: true
  external:
   name: api_network